name:                aoc-2023hs
version:             0.1.0.0
github:              "githubuser/aoc-2023hs"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aoc-2023hs#readme>

dependencies:
- base >= 4.7 && < 5
- text
- unordered-containers
- split
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -O2
  #- -fprof-auto

library:
  source-dirs: src

executables:
  aoc-n05-exe:
    main:               n05.hs
    source-dirs:        src
    dependencies:
    - aoc-2023hs
  aoc-n04-exe:
    main:               n04.hs
    source-dirs:        src
    dependencies:
    - aoc-2023hs
  aoc-n07-exe:
    main:               n07.hs
    source-dirs:        src
    dependencies:
    - aoc-2023hs
  aoc-n08-exe:
    main:               n08.hs
    source-dirs:        src
    dependencies:
    - aoc-2023hs

  aoc-2023hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc-2023hs

tests:
  aoc-2023hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc-2023hs
