name:                aoc-2023hs
version:             0.1.0.0
github:              "githubuser/aoc-2023hs"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aoc-2023hs#readme>

dependencies:
- base >= 4.7 && < 5
- text
- unordered-containers
- split
- megaparsec

default-extensions:
- BangPatterns
- DeriveGeneric
- DuplicateRecordFields
- EmptyCase
- FlexibleContexts
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- LambdaCase
- MultiWayIf
- NamedFieldPuns
- NondecreasingIndentation
- NumericUnderscores
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeFamilies
- UndecidableInstances

ghc-options:
- -Wall
- -Werror
- -Wno-name-shadowing
- -O2

library:
  source-dirs: src

executables:
  aoc-2023hs-exe:
    main:                app/main.hs
    dependencies:
    - aoc-2023hs
